// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mindmap} from '../models';
import {main} from '../models';

export function ExportMarkdown(arg1:mindmap.MindMap):Promise<void>;

export function GetClipboardImage():Promise<string>;

export function GetCurrentFilePath():Promise<string>;

export function GetPendingFile():Promise<string>;

export function ImportFile():Promise<main.ImportResult>;

export function LoadImageFile():Promise<string>;

export function NewFile():Promise<mindmap.MindMap>;

export function OpenFile():Promise<mindmap.MindMap>;

export function OpenFileByPath(arg1:string):Promise<mindmap.MindMap>;

export function SaveAsFile(arg1:mindmap.MindMap):Promise<string>;

export function SaveFile(arg1:mindmap.MindMap):Promise<string>;

export function SetFrontendReady():Promise<void>;
