// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportMarkdown(arg1) {
  return window['go']['main']['App']['ExportMarkdown'](arg1);
}

export function GetClipboardImage() {
  return window['go']['main']['App']['GetClipboardImage']();
}

export function GetCurrentFilePath() {
  return window['go']['main']['App']['GetCurrentFilePath']();
}

export function GetPendingFile() {
  return window['go']['main']['App']['GetPendingFile']();
}

export function ImportFile() {
  return window['go']['main']['App']['ImportFile']();
}

export function LoadImageFile() {
  return window['go']['main']['App']['LoadImageFile']();
}

export function NewFile() {
  return window['go']['main']['App']['NewFile']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function OpenFileByPath(arg1) {
  return window['go']['main']['App']['OpenFileByPath'](arg1);
}

export function SaveAsFile(arg1) {
  return window['go']['main']['App']['SaveAsFile'](arg1);
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}

export function SetFrontendReady() {
  return window['go']['main']['App']['SetFrontendReady']();
}
